# Generated by Django 5.1.3 on 2025-11-07 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactorTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('fecha', models.DateField()),
                ('resultado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.factortributario')),
            ],
        ),
    ]
