# Generated by Django 5.2.8 on 2025-11-08 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionEncabezado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.CharField(choices=[('ACCIONES', 'ACCIONES'), ('BONOS', 'BONOS'), ('FONDOS', 'FONDOS'), ('AC', 'AC'), ('BC', 'BC')], max_length=20)),
                ('origen', models.CharField(blank=True, choices=[('CORREDOR', 'CORREDOR'), ('DEPOSITARIO', 'DEPOSITARIO'), ('EMISOR', 'EMISOR')], max_length=20)),
                ('instrumento', models.CharField(max_length=100)),
                ('evento_capital', models.CharField(max_length=100)),
                ('valor_historico', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('fecha_pago', models.DateField()),
                ('secuencia_evento', models.PositiveIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('factor_actualizacion', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('sfut', models.BooleanField(default=False)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('ingreso_por_montos', models.BooleanField(default=False)),
                ('pendiente', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-actualizado'],
                'indexes': [models.Index(fields=['anio', 'mercado', 'origen'], name='calificacio_anio_7b2515_idx'), models.Index(fields=['instrumento'], name='calificacio_instrum_ca62c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalificacionFactores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f08', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f09', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f10', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f11', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f12', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f13', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f14', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f15', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f16', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f17', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f18', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f19a', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f20', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f21', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f22', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f23', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f24', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f25', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f26', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f27', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f28', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f29', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f30', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f31', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f32', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f33', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f34', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f35', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f36', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f37', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('f38_desc', models.CharField(blank=True, max_length=255)),
                ('encabezado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factores', to='calificaciones.calificacionencabezado')),
            ],
        ),
        migrations.DeleteModel(
            name='CalificacionTributaria',
        ),
        migrations.DeleteModel(
            name='FactorTributario',
        ),
    ]
