# Generated by Django 5.2.8 on 2025-11-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacionfactores',
            name='f38_desc',
        ),
        migrations.AlterField(
            model_name='calificacionencabezado',
            name='evento_capital',
            field=models.PositiveIntegerField(),
        ),
    ]
