# Generated by Django 5.2.8 on 2025-11-12 18:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0004_remove_calificacionfactores_f38_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacionencabezado',
            name='valor_historico',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0E-8'), max_digits=18, null=True),
        ),
    ]
