# Generated by Django 5.2.8 on 2025-11-12 18:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0005_alter_calificacionencabezado_valor_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacionencabezado',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calificacionencabezado',
            name='factor_actualizacion',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0E-8'), max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='calificacionencabezado',
            name='secuencia_evento',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
