# Generated by Django 5.2.8 on 2025-11-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0006_alter_calificacionencabezado_anio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacionencabezado',
            name='evento_capital',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
