# Generated by Django 5.2.8 on 2025-11-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0007_alter_calificacionencabezado_evento_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacionencabezado',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calificacionencabezado',
            name='factor_actualizacion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calificacionencabezado',
            name='valor_historico',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
